export { guessLanguage, type GuessedLanguage } from './guessLanguage'
export { isJson } from './isJson'
export { isHtml } from './isHtml'
export { isCss } from './isCss'
export { isShell } from './isShell'
export { isPython } from './isPython'
export { isSql } from './isSql'
export { isYaml } from './isYaml'
export { isMarkdown } from './isMarkdown'
export { isTypeScript } from './isTypeScript'
