mod blame;
mod bisect;
mod am;
mod apply_patch;
mod archive;
mod branch_create;
mod branch_delete;
mod branch_rename;
mod checkout_branch;
mod cherry_pick;
mod cherry_pick_abort;
mod cherry_pick_continue;
mod clean;
mod clone;
mod cmd_get_git_remote_url;
mod cmd_git_blame;
mod commit;
mod commit_amend;
mod config_get;
mod config_set;
mod describe;
mod discard_changes;
mod fetch;
mod format_patch;
mod get_branches;
mod get_commit_context;
mod get_diff;
mod get_git_branch;
mod get_git_commit_calendar;
mod get_git_commit_count;
mod get_git_log;
mod get_git_status;
mod get_git_worktrees;
mod get_local_file_at_commit;
mod get_local_file_git_history;
mod grep;
mod init;
mod is_local_git_repo;
mod ls_files;
mod ls_tree;
mod merge;
mod merge_abort;
mod merge_continue;
mod notes_add;
mod notes_remove;
mod notes_show;
mod operation_state;
mod pull;
mod push;
mod rebase;
mod rebase_abort;
mod rebase_continue;
mod rebase_skip;
mod reflog;
mod reset;
mod restore;
mod revert;
mod run_git_no_editor;
mod run_git_or_conflict;
mod show;
mod snapshot;
mod stage_files;
mod stash_apply;
mod stash_drop;
mod stash_list;
mod stash_pop;
mod stash_save;
mod stash_show;
mod submodule_add;
mod submodule_status;
mod submodule_sync;
mod submodule_update;
mod tag_create;
mod tag_delete;
mod tag_list;
mod tag_push;
mod remote_add;
mod remote_list;
mod remote_remove;
mod remote_set_url;
mod worktree_add;
mod worktree_prune;
mod worktree_remove;
mod unstage_files;
pub mod watcher;

pub use checkout_branch::*;
pub use cmd_get_git_remote_url::*;
pub use cmd_git_blame::*;
pub use commit::*;
pub use commit_amend::*;
pub use bisect::*;
pub use branch_create::*;
pub use branch_delete::*;
pub use branch_rename::*;
pub use cherry_pick::*;
pub use cherry_pick_abort::*;
pub use cherry_pick_continue::*;
pub use clean::*;
pub use discard_changes::*;
pub use fetch::*;
pub use get_branches::*;
pub use get_commit_context::*;
pub use get_diff::*;
pub use get_git_branch::*;
pub use get_git_commit_calendar::*;
pub use get_git_commit_count::*;
pub use get_git_log::*;
pub use get_git_status::*;
pub use get_git_worktrees::*;
pub use get_local_file_at_commit::*;
pub use get_local_file_git_history::*;
pub use is_local_git_repo::*;
pub use merge::*;
pub use merge_abort::*;
pub use merge_continue::*;
pub use operation_state::*;
pub use pull::*;
pub use push::*;
pub use rebase::*;
pub use rebase_abort::*;
pub use rebase_continue::*;
pub use rebase_skip::*;
pub use reflog::*;
pub use reset::*;
pub use restore::*;
pub use revert::*;
pub use snapshot::*;
pub use stage_files::*;
pub use stash_apply::*;
pub use stash_drop::*;
pub use stash_list::*;
pub use stash_pop::*;
pub use stash_save::*;
pub use stash_show::*;
pub use submodule_add::*;
pub use submodule_status::*;
pub use submodule_sync::*;
pub use submodule_update::*;
pub use tag_create::*;
pub use tag_delete::*;
pub use tag_list::*;
pub use tag_push::*;
pub use remote_add::*;
pub use remote_list::*;
pub use remote_remove::*;
pub use remote_set_url::*;
pub use worktree_add::*;
pub use worktree_prune::*;
pub use worktree_remove::*;
pub use unstage_files::*;
// Phase 5 — patches / archive / notes / inspection / config / clone / init
pub use am::*;
pub use apply_patch::*;
pub use archive::*;
pub use clone::*;
pub use config_get::*;
pub use config_set::*;
pub use describe::*;
pub use format_patch::*;
pub use grep::*;
pub use init::*;
pub use ls_files::*;
pub use ls_tree::*;
pub use notes_add::*;
pub use notes_remove::*;
pub use notes_show::*;
pub use show::*;
// `watcher` is now a thin re-export shim around `fs_watcher::mark_self_write`;
// the start/stop Tauri commands have moved to `fs_watcher`.
pub use watcher::mark_self_write;
