export const TERMINAL_LINE_HEIGHT_MIN = 0.8
export const TERMINAL_LINE_HEIGHT_MAX = 2.5
export const TERMINAL_LINE_HEIGHT_DEFAULT = 1.2
export const TERMINAL_LINE_HEIGHT_STEP = 0.1
export const TERMINAL_LINE_HEIGHT_DECIMALS = 1
