const MIME_CATEGORY_MAP: Record<string, string> = {
  ts: 'Code',
  tsx: 'Code',
  js: 'Code',
  jsx: 'Code',
  mjs: 'Code',
  cjs: 'Code',
  py: 'Code',
  rb: 'Code',
  go: 'Code',
  rs: 'Code',
  java: 'Code',
  kt: 'Code',
  swift: 'Code',
  c: 'Code',
  h: 'Code',
  cpp: 'Code',
  hpp: 'Code',
  cc: 'Code',
  cs: 'Code',
  php: 'Code',
  sh: 'Code',
  bash: 'Code',
  zsh: 'Code',
  fish: 'Code',
  lua: 'Code',
  pl: 'Code',
  r: 'Code',
  sql: 'Code',
  html: 'Markup',
  htm: 'Markup',
  xml: 'Markup',
  svg: 'Markup',
  vue: 'Markup',
  css: 'Style',
  scss: 'Style',
  sass: 'Style',
  less: 'Style',
  styl: 'Style',
  json: 'Data',
  json5: 'Data',
  jsonc: 'Data',
  yaml: 'Data',
  yml: 'Data',
  toml: 'Data',
  csv: 'Data',
  tsv: 'Data',
  md: 'Doc',
  mdx: 'Doc',
  txt: 'Doc',
  rst: 'Doc',
  adoc: 'Doc',
  pdf: 'Doc',
  doc: 'Doc',
  docx: 'Doc',
  rtf: 'Doc',
  png: 'Image',
  jpg: 'Image',
  jpeg: 'Image',
  gif: 'Image',
  webp: 'Image',
  bmp: 'Image',
  ico: 'Image',
  tif: 'Image',
  tiff: 'Image',
  avif: 'Image',
  heic: 'Image',
  mp3: 'Audio',
  wav: 'Audio',
  ogg: 'Audio',
  flac: 'Audio',
  m4a: 'Audio',
  aac: 'Audio',
  opus: 'Audio',
  mp4: 'Video',
  mov: 'Video',
  avi: 'Video',
  mkv: 'Video',
  webm: 'Video',
  m4v: 'Video',
  wmv: 'Video',
  zip: 'Archive',
  tar: 'Archive',
  gz: 'Archive',
  tgz: 'Archive',
  bz2: 'Archive',
  xz: 'Archive',
  '7z': 'Archive',
  rar: 'Archive',
  exe: 'Binary',
  dll: 'Binary',
  so: 'Binary',
  dylib: 'Binary',
  bin: 'Binary',
  o: 'Binary',
  a: 'Binary',
  obj: 'Binary',
  class: 'Binary',
  wasm: 'Binary',
}

export function getMimeCategory(name: string): string {
  const dotIndex = name.lastIndexOf('.')
  if (dotIndex < 0) return 'File'
  const ext = name.slice(dotIndex + 1).toLowerCase()
  if (!ext) return 'File'
  return MIME_CATEGORY_MAP[ext] ?? 'File'
}
