import type { TerminalTheme, TerminalThemeColors } from './terminalThemes.types'

/**
 * The 16 ANSI colors shared by the classic macOS Terminal.app profiles. Each
 * profile overrides only background / foreground / cursor / selection, so the
 * palette is factored out here and spread into every macOS theme below.
 */
const MACOS_ANSI: Omit<
  TerminalThemeColors,
  'background' | 'foreground' | 'cursor' | 'cursorAccent' | 'selectionBackground'
> = {
  black: '#000000',
  red: '#990000',
  green: '#00a600',
  yellow: '#999900',
  blue: '#0000b2',
  magenta: '#b200b2',
  cyan: '#00a6b2',
  white: '#bfbfbf',
  brightBlack: '#666666',
  brightRed: '#e50000',
  brightGreen: '#00d900',
  brightYellow: '#e5e500',
  brightBlue: '#0000ff',
  brightMagenta: '#e500e5',
  brightCyan: '#00e5e5',
  brightWhite: '#e5e5e5',
}

/**
 * The Tango palette (GNOME Terminal) shared by the Ubuntu and Tango profiles.
 * Each profile overrides only background / foreground / cursor / selection, so
 * the 16 ANSI colors are factored out here and spread into every Tango theme.
 */
const TANGO_ANSI: Omit<
  TerminalThemeColors,
  'background' | 'foreground' | 'cursor' | 'cursorAccent' | 'selectionBackground'
> = {
  black: '#2e3436',
  red: '#cc0000',
  green: '#4e9a06',
  yellow: '#c4a000',
  blue: '#3465a4',
  magenta: '#75507b',
  cyan: '#06989a',
  white: '#d3d7cf',
  brightBlack: '#555753',
  brightRed: '#ef2929',
  brightGreen: '#8ae234',
  brightYellow: '#fce94f',
  brightBlue: '#729fcf',
  brightMagenta: '#ad7fa8',
  brightCyan: '#34e2e2',
  brightWhite: '#eeeeec',
}

/**
 * Curated terminal color schemes selectable per tab. Order within each group is
 * the order shown in the menu; groups themselves are ordered by
 * `TERMINAL_THEME_GROUP_ORDER` in `index.ts`.
 */
export const TERMINAL_THEMES: TerminalTheme[] = [
  // ── Popular developer schemes ──────────────────────────────────────────────
  {
    id: 'dracula',
    name: 'Dracula',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      selectionBackground: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      selectionBackground: '#3e4451',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selectionBackground: '#283457',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  {
    id: 'tomorrow-night',
    name: 'Tomorrow Night',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#1d1f21',
      foreground: '#c5c8c6',
      cursor: '#c5c8c6',
      selectionBackground: '#373b41',
      black: '#1d1f21',
      red: '#cc6666',
      green: '#b5bd68',
      yellow: '#f0c674',
      blue: '#81a2be',
      magenta: '#b294bb',
      cyan: '#8abeb7',
      white: '#c5c8c6',
      brightBlack: '#969896',
      brightRed: '#cc6666',
      brightGreen: '#b5bd68',
      brightYellow: '#f0c674',
      brightBlue: '#81a2be',
      brightMagenta: '#b294bb',
      brightCyan: '#8abeb7',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      cursor: '#f8f8f0',
      selectionBackground: '#49483e',
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      selectionBackground: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#011627',
      foreground: '#d6deeb',
      cursor: '#80a4c2',
      selectionBackground: '#1d3b53',
      black: '#011627',
      red: '#ef5350',
      green: '#22da6e',
      yellow: '#addb67',
      blue: '#82aaff',
      magenta: '#c792ea',
      cyan: '#21c7a8',
      white: '#ffffff',
      brightBlack: '#637777',
      brightRed: '#ef5350',
      brightGreen: '#22da6e',
      brightYellow: '#ffeb95',
      brightBlue: '#82aaff',
      brightMagenta: '#c792ea',
      brightCyan: '#7fdbca',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'snazzy',
    name: 'Snazzy',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#282a36',
      foreground: '#eff0eb',
      cursor: '#97979b',
      selectionBackground: '#343746',
      black: '#282a36',
      red: '#ff5c57',
      green: '#5af78e',
      yellow: '#f3f99d',
      blue: '#57c7ff',
      magenta: '#ff6ac1',
      cyan: '#9aedfe',
      white: '#f1f1f0',
      brightBlack: '#686868',
      brightRed: '#ff5c57',
      brightGreen: '#5af78e',
      brightYellow: '#f3f99d',
      brightBlue: '#57c7ff',
      brightMagenta: '#ff6ac1',
      brightCyan: '#9aedfe',
      brightWhite: '#eff0eb',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    group: 'Popular',
    isDark: true,
    colors: {
      background: '#002b36',
      foreground: '#839496',
      cursor: '#93a1a1',
      selectionBackground: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },

  // ── Modern editor schemes ──────────────────────────────────────────────────
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: '#585b70',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#24273a',
      foreground: '#cad3f5',
      cursor: '#f4dbd6',
      selectionBackground: '#5b6078',
      black: '#494d64',
      red: '#ed8796',
      green: '#a6da95',
      yellow: '#eed49f',
      blue: '#8aadf4',
      magenta: '#f5bde6',
      cyan: '#8bd5ca',
      white: '#b8c0e0',
      brightBlack: '#5b6078',
      brightRed: '#ed8796',
      brightGreen: '#a6da95',
      brightYellow: '#eed49f',
      brightBlue: '#8aadf4',
      brightMagenta: '#f5bde6',
      brightCyan: '#8bd5ca',
      brightWhite: '#a5adcb',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#191724',
      foreground: '#e0def4',
      cursor: '#524f67',
      selectionBackground: '#403d52',
      black: '#26233a',
      red: '#eb6f92',
      green: '#31748f',
      yellow: '#f6c177',
      blue: '#9ccfd8',
      magenta: '#c4a7e7',
      cyan: '#ebbcba',
      white: '#e0def4',
      brightBlack: '#6e6a86',
      brightRed: '#eb6f92',
      brightGreen: '#31748f',
      brightYellow: '#f6c177',
      brightBlue: '#9ccfd8',
      brightMagenta: '#c4a7e7',
      brightCyan: '#ebbcba',
      brightWhite: '#e0def4',
    },
  },
  {
    id: 'rose-pine-moon',
    name: 'Rosé Pine Moon',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#232136',
      foreground: '#e0def4',
      cursor: '#56526e',
      selectionBackground: '#44415a',
      black: '#393552',
      red: '#eb6f92',
      green: '#3e8fb0',
      yellow: '#f6c177',
      blue: '#9ccfd8',
      magenta: '#c4a7e7',
      cyan: '#ea9a97',
      white: '#e0def4',
      brightBlack: '#6e6a86',
      brightRed: '#eb6f92',
      brightGreen: '#3e8fb0',
      brightYellow: '#f6c177',
      brightBlue: '#9ccfd8',
      brightMagenta: '#c4a7e7',
      brightCyan: '#ea9a97',
      brightWhite: '#e0def4',
    },
  },
  {
    id: 'kanagawa',
    name: 'Kanagawa',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#1f1f28',
      foreground: '#dcd7ba',
      cursor: '#c8c093',
      selectionBackground: '#2d4f67',
      black: '#16161d',
      red: '#c34043',
      green: '#76946a',
      yellow: '#c0a36e',
      blue: '#7e9cd8',
      magenta: '#957fb8',
      cyan: '#6a9589',
      white: '#c8c093',
      brightBlack: '#727169',
      brightRed: '#e82424',
      brightGreen: '#98bb6c',
      brightYellow: '#e6c384',
      brightBlue: '#7fb4ca',
      brightMagenta: '#938aa9',
      brightCyan: '#7aa89f',
      brightWhite: '#dcd7ba',
    },
  },
  {
    id: 'everforest-dark',
    name: 'Everforest Dark',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#2d353b',
      foreground: '#d3c6aa',
      cursor: '#d3c6aa',
      selectionBackground: '#475258',
      black: '#475258',
      red: '#e67e80',
      green: '#a7c080',
      yellow: '#dbbc7f',
      blue: '#7fbbb3',
      magenta: '#d699b6',
      cyan: '#83c092',
      white: '#d3c6aa',
      brightBlack: '#56635f',
      brightRed: '#e67e80',
      brightGreen: '#a7c080',
      brightYellow: '#dbbc7f',
      brightBlue: '#7fbbb3',
      brightMagenta: '#d699b6',
      brightCyan: '#83c092',
      brightWhite: '#d3c6aa',
    },
  },
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#0b0e14',
      foreground: '#bfbdb6',
      cursor: '#e6b450',
      selectionBackground: '#1e2730',
      black: '#01060e',
      red: '#ea6c73',
      green: '#91b362',
      yellow: '#f9af4f',
      blue: '#53bdfa',
      magenta: '#fae994',
      cyan: '#90e1c6',
      white: '#c7c7c7',
      brightBlack: '#686868',
      brightRed: '#f07178',
      brightGreen: '#c2d94c',
      brightYellow: '#ffb454',
      brightBlue: '#59c2ff',
      brightMagenta: '#ffee99',
      brightCyan: '#95e6cb',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'ayu-mirage',
    name: 'Ayu Mirage',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#1f2430',
      foreground: '#cccac2',
      cursor: '#ffcc66',
      selectionBackground: '#34455a',
      black: '#191e2a',
      red: '#ed8274',
      green: '#a6cc70',
      yellow: '#fad07b',
      blue: '#6dcbfa',
      magenta: '#cfbafa',
      cyan: '#90e1c6',
      white: '#c7c7c7',
      brightBlack: '#686868',
      brightRed: '#f28779',
      brightGreen: '#bae67e',
      brightYellow: '#ffd580',
      brightBlue: '#73d0ff',
      brightMagenta: '#d4bfff',
      brightCyan: '#95e6cb',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'tokyo-night-storm',
    name: 'Tokyo Night Storm',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#24283b',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selectionBackground: '#2e3c64',
      black: '#1d202f',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      cursor: '#c9d1d9',
      selectionBackground: '#163356',
      black: '#484f58',
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
      white: '#b1bac4',
      brightBlack: '#6e7681',
      brightRed: '#ffa198',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#79c0ff',
      brightMagenta: '#d2a8ff',
      brightCyan: '#56d4dd',
      brightWhite: '#f0f6fc',
    },
  },
  {
    id: 'palenight',
    name: 'Palenight',
    group: 'Modern',
    isDark: true,
    colors: {
      background: '#292d3e',
      foreground: '#a6accd',
      cursor: '#ffcc00',
      selectionBackground: '#3c435e',
      black: '#292d3e',
      red: '#f07178',
      green: '#c3e88d',
      yellow: '#ffcb6b',
      blue: '#82aaff',
      magenta: '#c792ea',
      cyan: '#89ddff',
      white: '#d0d0d0',
      brightBlack: '#434758',
      brightRed: '#ff8b92',
      brightGreen: '#ddffa7',
      brightYellow: '#ffe585',
      brightBlue: '#9cc4ff',
      brightMagenta: '#e1acff',
      brightCyan: '#a3f7ff',
      brightWhite: '#ffffff',
    },
  },

  // ── Vibrant / neon schemes ─────────────────────────────────────────────────
  {
    id: 'synthwave-84',
    name: "Synthwave '84",
    group: 'Vibrant',
    isDark: true,
    colors: {
      background: '#262335',
      foreground: '#f0eff1',
      cursor: '#ff7edb',
      selectionBackground: '#463465',
      black: '#262335',
      red: '#fe4450',
      green: '#72f1b8',
      yellow: '#fede5d',
      blue: '#03edf9',
      magenta: '#ff7edb',
      cyan: '#03edf9',
      white: '#ffffff',
      brightBlack: '#495495',
      brightRed: '#fe4450',
      brightGreen: '#72f1b8',
      brightYellow: '#fede5d',
      brightBlue: '#03edf9',
      brightMagenta: '#ff7edb',
      brightCyan: '#03edf9',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    group: 'Vibrant',
    isDark: true,
    colors: {
      background: '#000b1e',
      foreground: '#0abdc6',
      cursor: '#ea00d9',
      selectionBackground: '#122140',
      black: '#123e7c',
      red: '#ff0000',
      green: '#d300c5',
      yellow: '#f57800',
      blue: '#123e7c',
      magenta: '#711c91',
      cyan: '#0abdc6',
      white: '#d7d7d5',
      brightBlack: '#1c61c2',
      brightRed: '#ff0000',
      brightGreen: '#d300c5',
      brightYellow: '#f57800',
      brightBlue: '#00ff00',
      brightMagenta: '#711c91',
      brightCyan: '#0abdc6',
      brightWhite: '#d7d7d5',
    },
  },
  {
    id: 'aura',
    name: 'Aura',
    group: 'Vibrant',
    isDark: true,
    colors: {
      background: '#15141b',
      foreground: '#edecee',
      cursor: '#a277ff',
      selectionBackground: '#29263c',
      black: '#110f18',
      red: '#ff6767',
      green: '#61ffca',
      yellow: '#ffca85',
      blue: '#a277ff',
      magenta: '#a277ff',
      cyan: '#61ffca',
      white: '#edecee',
      brightBlack: '#4d4d4d',
      brightRed: '#ff6767',
      brightGreen: '#61ffca',
      brightYellow: '#ffca85',
      brightBlue: '#a277ff',
      brightMagenta: '#a277ff',
      brightCyan: '#61ffca',
      brightWhite: '#edecee',
    },
  },
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    group: 'Vibrant',
    isDark: true,
    colors: {
      background: '#193549',
      foreground: '#ffffff',
      cursor: '#ffc600',
      selectionBackground: '#234d70',
      black: '#000000',
      red: '#ff628c',
      green: '#3ad900',
      yellow: '#e9c062',
      blue: '#0088ff',
      magenta: '#ff6dff',
      cyan: '#00bbbb',
      white: '#bbbbbb',
      brightBlack: '#555555',
      brightRed: '#ff628c',
      brightGreen: '#3ad900',
      brightYellow: '#e9c062',
      brightBlue: '#0088ff',
      brightMagenta: '#ff6dff',
      brightCyan: '#6ae3f9',
      brightWhite: '#ffffff',
    },
  },

  // ── Classic macOS Terminal.app profiles ────────────────────────────────────
  {
    id: 'macos-basic',
    name: 'Basic',
    group: 'macOS',
    isDark: false,
    colors: {
      background: '#ffffff',
      foreground: '#000000',
      cursor: '#000000',
      cursorAccent: '#ffffff',
      selectionBackground: '#b4d5fe',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-pro',
    name: 'Pro',
    group: 'macOS',
    isDark: true,
    colors: {
      background: '#000000',
      foreground: '#f2f2f2',
      cursor: '#4d4d4d',
      selectionBackground: '#525252',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-homebrew',
    name: 'Homebrew',
    group: 'macOS',
    isDark: true,
    colors: {
      background: '#000000',
      foreground: '#00ff00',
      cursor: '#23ff18',
      selectionBackground: '#006000',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-novel',
    name: 'Novel',
    group: 'macOS',
    isDark: false,
    colors: {
      background: '#dfdbc3',
      foreground: '#3b2322',
      cursor: '#73635a',
      selectionBackground: '#a4a390',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-ocean',
    name: 'Ocean',
    group: 'macOS',
    isDark: true,
    colors: {
      background: '#224fbc',
      foreground: '#ffffff',
      cursor: '#7f7f7f',
      selectionBackground: '#216dff',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-man-page',
    name: 'Man Page',
    group: 'macOS',
    isDark: false,
    colors: {
      background: '#fef49c',
      foreground: '#000000',
      cursor: '#7f7f7f',
      cursorAccent: '#fef49c',
      selectionBackground: '#a4c9ff',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-red-sand',
    name: 'Red Sand',
    group: 'macOS',
    isDark: true,
    colors: {
      background: '#7a251e',
      foreground: '#d7c9a7',
      cursor: '#ffffff',
      selectionBackground: '#9a3b34',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-grass',
    name: 'Grass',
    group: 'macOS',
    isDark: true,
    colors: {
      background: '#13773d',
      foreground: '#fff0a5',
      cursor: '#8c1400',
      selectionBackground: '#0e5f2f',
      ...MACOS_ANSI,
    },
  },
  {
    id: 'macos-silver-aerogel',
    name: 'Silver Aerogel',
    group: 'macOS',
    isDark: false,
    colors: {
      background: '#929292',
      foreground: '#000000',
      cursor: '#000000',
      cursorAccent: '#929292',
      selectionBackground: '#c1deff',
      ...MACOS_ANSI,
    },
  },

  // ── Windows Terminal / Console schemes ─────────────────────────────────────
  {
    id: 'campbell',
    name: 'Campbell',
    group: 'Windows',
    isDark: true,
    colors: {
      background: '#0c0c0c',
      foreground: '#cccccc',
      cursor: '#cccccc',
      selectionBackground: '#264f78',
      black: '#0c0c0c',
      red: '#c50f1f',
      green: '#13a10e',
      yellow: '#c19c00',
      blue: '#0037da',
      magenta: '#881798',
      cyan: '#3a96dd',
      white: '#cccccc',
      brightBlack: '#767676',
      brightRed: '#e74856',
      brightGreen: '#16c60c',
      brightYellow: '#f9f1a5',
      brightBlue: '#3b78ff',
      brightMagenta: '#b4009e',
      brightCyan: '#61d6d6',
      brightWhite: '#f2f2f2',
    },
  },
  {
    id: 'campbell-powershell',
    name: 'Campbell PowerShell',
    group: 'Windows',
    isDark: true,
    colors: {
      background: '#012456',
      foreground: '#cccccc',
      cursor: '#cccccc',
      selectionBackground: '#264f78',
      black: '#0c0c0c',
      red: '#c50f1f',
      green: '#13a10e',
      yellow: '#c19c00',
      blue: '#0037da',
      magenta: '#881798',
      cyan: '#3a96dd',
      white: '#cccccc',
      brightBlack: '#767676',
      brightRed: '#e74856',
      brightGreen: '#16c60c',
      brightYellow: '#f9f1a5',
      brightBlue: '#3b78ff',
      brightMagenta: '#b4009e',
      brightCyan: '#61d6d6',
      brightWhite: '#f2f2f2',
    },
  },
  {
    id: 'vintage',
    name: 'Vintage',
    group: 'Windows',
    isDark: true,
    colors: {
      background: '#000000',
      foreground: '#c0c0c0',
      cursor: '#c0c0c0',
      selectionBackground: '#808080',
      black: '#000000',
      red: '#800000',
      green: '#008000',
      yellow: '#808000',
      blue: '#000080',
      magenta: '#800080',
      cyan: '#008080',
      white: '#c0c0c0',
      brightBlack: '#808080',
      brightRed: '#ff0000',
      brightGreen: '#00ff00',
      brightYellow: '#ffff00',
      brightBlue: '#0000ff',
      brightMagenta: '#ff00ff',
      brightCyan: '#00ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'one-half-dark',
    name: 'One Half Dark',
    group: 'Windows',
    isDark: true,
    colors: {
      background: '#282c34',
      foreground: '#dcdfe4',
      cursor: '#a3b3cc',
      selectionBackground: '#474e5d',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#dcdfe4',
      brightBlack: '#5a6374',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#dcdfe4',
    },
  },
  {
    id: 'one-half-light',
    name: 'One Half Light',
    group: 'Windows',
    isDark: false,
    colors: {
      background: '#fafafa',
      foreground: '#383a42',
      cursor: '#4f525e',
      cursorAccent: '#fafafa',
      selectionBackground: '#bfceff',
      black: '#383a42',
      red: '#e45649',
      green: '#50a14f',
      yellow: '#c18401',
      blue: '#0184bc',
      magenta: '#a626a4',
      cyan: '#0997b3',
      white: '#fafafa',
      brightBlack: '#4f525e',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
  },

  // ── Linux distro & console schemes ─────────────────────────────────────────
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    group: 'Linux',
    isDark: true,
    colors: {
      background: '#300a24',
      foreground: '#ffffff',
      cursor: '#ffffff',
      selectionBackground: '#5a1145',
      ...TANGO_ANSI,
    },
  },
  {
    id: 'tango-dark',
    name: 'Tango Dark',
    group: 'Linux',
    isDark: true,
    colors: {
      background: '#2e3436',
      foreground: '#d3d7cf',
      cursor: '#d3d7cf',
      selectionBackground: '#555753',
      ...TANGO_ANSI,
    },
  },
  {
    id: 'tango-light',
    name: 'Tango Light',
    group: 'Linux',
    isDark: false,
    colors: {
      background: '#ffffff',
      foreground: '#2e3436',
      cursor: '#2e3436',
      cursorAccent: '#ffffff',
      selectionBackground: '#c7c7c7',
      ...TANGO_ANSI,
    },
  },
  {
    id: 'breeze',
    name: 'Breeze',
    group: 'Linux',
    isDark: true,
    colors: {
      background: '#232627',
      foreground: '#fcfcfc',
      cursor: '#fcfcfc',
      selectionBackground: '#2a4f6b',
      black: '#232627',
      red: '#ed1515',
      green: '#11d116',
      yellow: '#f67400',
      blue: '#1d99f3',
      magenta: '#9b59b6',
      cyan: '#1abc9c',
      white: '#fcfcfc',
      brightBlack: '#7f8c8d',
      brightRed: '#c0392b',
      brightGreen: '#1cdc9a',
      brightYellow: '#fdbc4b',
      brightBlue: '#3daee9',
      brightMagenta: '#8e44ad',
      brightCyan: '#16a085',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'linux-console',
    name: 'Linux Console',
    group: 'Linux',
    isDark: true,
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      cursor: '#ffffff',
      selectionBackground: '#444444',
      black: '#000000',
      red: '#aa0000',
      green: '#00aa00',
      yellow: '#aa5500',
      blue: '#0000aa',
      magenta: '#aa00aa',
      cyan: '#00aaaa',
      white: '#aaaaaa',
      brightBlack: '#555555',
      brightRed: '#ff5555',
      brightGreen: '#55ff55',
      brightYellow: '#ffff55',
      brightBlue: '#5555ff',
      brightMagenta: '#ff55ff',
      brightCyan: '#55ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'xterm',
    name: 'XTerm',
    group: 'Linux',
    isDark: true,
    colors: {
      background: '#000000',
      foreground: '#e5e5e5',
      cursor: '#e5e5e5',
      selectionBackground: '#333333',
      black: '#000000',
      red: '#cd0000',
      green: '#00cd00',
      yellow: '#cdcd00',
      blue: '#0000ee',
      magenta: '#cd00cd',
      cyan: '#00cdcd',
      white: '#e5e5e5',
      brightBlack: '#7f7f7f',
      brightRed: '#ff0000',
      brightGreen: '#00ff00',
      brightYellow: '#ffff00',
      brightBlue: '#5c5cff',
      brightMagenta: '#ff00ff',
      brightCyan: '#00ffff',
      brightWhite: '#ffffff',
    },
  },

  // ── Light schemes ──────────────────────────────────────────────────────────
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#586e75',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#fbf1c7',
      foreground: '#3c3836',
      cursor: '#3c3836',
      cursorAccent: '#fbf1c7',
      selectionBackground: '#ebdbb2',
      black: '#fbf1c7',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#7c6f64',
      brightBlack: '#928374',
      brightRed: '#9d0006',
      brightGreen: '#79740e',
      brightYellow: '#b57614',
      brightBlue: '#076678',
      brightMagenta: '#8f3f71',
      brightCyan: '#427b58',
      brightWhite: '#3c3836',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#ffffff',
      foreground: '#24292e',
      cursor: '#24292e',
      cursorAccent: '#ffffff',
      selectionBackground: '#c8e1ff',
      black: '#24292e',
      red: '#d73a49',
      green: '#28a745',
      yellow: '#dbab09',
      blue: '#0366d6',
      magenta: '#5a32a3',
      cyan: '#0598bc',
      white: '#6a737d',
      brightBlack: '#959da5',
      brightRed: '#cb2431',
      brightGreen: '#22863a',
      brightYellow: '#b08800',
      brightBlue: '#005cc5',
      brightMagenta: '#5a32a3',
      brightCyan: '#3192aa',
      brightWhite: '#d1d5da',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      cursorAccent: '#eff1f5',
      selectionBackground: '#bcc0cc',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#faf4ed',
      foreground: '#575279',
      cursor: '#575279',
      cursorAccent: '#faf4ed',
      selectionBackground: '#dfdad9',
      black: '#f2e9e1',
      red: '#b4637a',
      green: '#286983',
      yellow: '#ea9d34',
      blue: '#56949f',
      magenta: '#907aa9',
      cyan: '#d7827e',
      white: '#575279',
      brightBlack: '#9893a5',
      brightRed: '#b4637a',
      brightGreen: '#286983',
      brightYellow: '#ea9d34',
      brightBlue: '#56949f',
      brightMagenta: '#907aa9',
      brightCyan: '#d7827e',
      brightWhite: '#575279',
    },
  },
  {
    id: 'ayu-light',
    name: 'Ayu Light',
    group: 'Light',
    isDark: false,
    colors: {
      background: '#fafafa',
      foreground: '#5c6166',
      cursor: '#ffaa33',
      cursorAccent: '#fafafa',
      selectionBackground: '#d1e4f4',
      black: '#000000',
      red: '#ea6c73',
      green: '#86b300',
      yellow: '#f2ae49',
      blue: '#399ee6',
      magenta: '#a37acc',
      cyan: '#4dbf99',
      white: '#c7c7c7',
      brightBlack: '#686868',
      brightRed: '#f07171',
      brightGreen: '#86b300',
      brightYellow: '#f2ae49',
      brightBlue: '#399ee6',
      brightMagenta: '#a37acc',
      brightCyan: '#4cbf99',
      brightWhite: '#d1d1d1',
    },
  },
]
