import type { ToolModule } from './tools.types'

import { DAILYPLAN_TOOL_DEFINITIONS, DAILYPLAN_TOOL_REGISTRY } from './daily-plan'
import { LIBRARY_TOOL_DEFINITIONS, LIBRARY_TOOL_REGISTRY } from './library'
import { NOTES_TOOL_DEFINITIONS, NOTES_TOOL_REGISTRY } from './notes'
import { API_CLIENT_TOOL_DEFINITIONS, API_CLIENT_TOOL_REGISTRY } from './api-client'
import { PROMPT_MANAGER_TOOL_DEFINITIONS, PROMPT_MANAGER_TOOL_REGISTRY } from './prompt-manager'
import { MOCKSERVER_TOOL_DEFINITIONS, MOCKSERVER_TOOL_REGISTRY } from './mock-server'
import { DASHBOARD_TOOL_DEFINITIONS, DASHBOARD_TOOL_REGISTRY } from './dashboard'
import { PROJECT_EXPLORER_TOOL_DEFINITIONS, PROJECT_EXPLORER_TOOL_REGISTRY } from './project-explorer'
import { CLIPBOARD_TOOL_DEFINITIONS, CLIPBOARD_TOOL_REGISTRY } from './clipboard'
import { MEMORY_TOOL_DEFINITIONS, MEMORY_TOOL_REGISTRY } from './memory'

/** All tool definitions across every app — sent to the AI API */
export const ALL_TOOL_DEFINITIONS = [
  ...DAILYPLAN_TOOL_DEFINITIONS,
  ...LIBRARY_TOOL_DEFINITIONS,
  ...NOTES_TOOL_DEFINITIONS,
  ...API_CLIENT_TOOL_DEFINITIONS,
  ...PROMPT_MANAGER_TOOL_DEFINITIONS,
  ...MOCKSERVER_TOOL_DEFINITIONS,
  ...DASHBOARD_TOOL_DEFINITIONS,
  ...PROJECT_EXPLORER_TOOL_DEFINITIONS,
  ...CLIPBOARD_TOOL_DEFINITIONS,
  ...MEMORY_TOOL_DEFINITIONS,
]

/** Unified tool registry — for dispatching any tool call by name */
export const ALL_TOOL_REGISTRY: Record<string, ToolModule> = {
  ...DAILYPLAN_TOOL_REGISTRY,
  ...LIBRARY_TOOL_REGISTRY,
  ...NOTES_TOOL_REGISTRY,
  ...API_CLIENT_TOOL_REGISTRY,
  ...PROMPT_MANAGER_TOOL_REGISTRY,
  ...MOCKSERVER_TOOL_REGISTRY,
  ...DASHBOARD_TOOL_REGISTRY,
  ...PROJECT_EXPLORER_TOOL_REGISTRY,
  ...CLIPBOARD_TOOL_REGISTRY,
  ...MEMORY_TOOL_REGISTRY,
}

export type { ToolModule, ToolResult, ToolExecuteContext } from './tools.types'
