const LANG_DISPLAY: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  tsx: 'React TSX',
  jsx: 'React JSX',
  py: 'Python',
  python: 'Python',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  less: 'Less',
  json: 'JSON',
  yaml: 'YAML',
  yml: 'YAML',
  bash: 'Bash',
  sh: 'Shell',
  shell: 'Shell',
  zsh: 'Zsh',
  sql: 'SQL',
  rust: 'Rust',
  rs: 'Rust',
  go: 'Go',
  java: 'Java',
  kotlin: 'Kotlin',
  kt: 'Kotlin',
  swift: 'Swift',
  c: 'C',
  cpp: 'C++',
  'c++': 'C++',
  csharp: 'C#',
  cs: 'C#',
  ruby: 'Ruby',
  rb: 'Ruby',
  php: 'PHP',
  dart: 'Dart',
  r: 'R',
  lua: 'Lua',
  xml: 'XML',
  toml: 'TOML',
  markdown: 'Markdown',
  md: 'Markdown',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  dockerfile: 'Dockerfile',
  docker: 'Docker',
  nginx: 'Nginx',
  prisma: 'Prisma',
}

export function getLangDisplayName(lang: string): string {
  const mapped = LANG_DISPLAY[lang]
  if (mapped) return mapped
  return lang.charAt(0).toUpperCase() + lang.slice(1)
}
