export { parseTimeToMinutes } from './utils/parseTimeToMinutes'
export { getCurrentTimeMinutes } from './utils/getCurrentTimeMinutes'
export { hasRangeOverlap } from './utils/hasRangeOverlap'
export { validateRanges } from './utils/validateRanges'
export { findActiveRange } from './utils/findActiveRange'
export { generateRangeId } from './utils/generateRangeId'
export { useAutoThemeScheduler } from './useAutoThemeScheduler'
export { MAX_SCHEDULE_RANGES, AUTO_THEME_DEFAULTS } from './autoThemeScheduler.types'
export type { ThemeScheduleRange, AutoThemeConfig } from './autoThemeScheduler.types'
