export const styles = {
  container: 'py-4',
  header: 'flex items-center justify-between mb-3',
  title: 'text-sm font-medium text-foreground',
  description: 'text-xs text-muted-foreground mt-0.5',
  serverList: 'space-y-2',
  serverCard: 'flex items-center justify-between p-3 rounded-lg border border-border/40 bg-card/50',
  serverInfo: 'flex items-center gap-2 min-w-0 flex-1',
  serverName: 'text-sm font-medium text-foreground truncate',
  serverMeta: 'text-xs text-muted-foreground',
  statusDot: {
    connected: 'w-2 h-2 rounded-full bg-emerald-500',
    connecting: 'w-2 h-2 rounded-full bg-amber-500 animate-pulse',
    disconnected: 'w-2 h-2 rounded-full bg-muted-foreground/40',
    error: 'w-2 h-2 rounded-full bg-destructive',
  },
  actions: 'flex items-center gap-1',
  form: 'mt-3 space-y-3 p-3 rounded-lg border border-border/40 bg-card/50',
  formField: 'space-y-1',
  formLabel: 'text-xs font-medium text-muted-foreground',
  formInput: 'w-full text-sm px-2.5 py-1.5 rounded-md border border-input bg-background text-foreground outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/30',
  formTextarea: 'w-full text-sm px-2.5 py-1.5 rounded-md border border-input bg-background text-foreground outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/30 resize-none font-mono',
  formActions: 'flex items-center gap-2 pt-1',
  emptyState: 'text-xs text-muted-foreground text-center py-6',
} as const
