export { detectUrl } from './detectUrl'
export { detectCode } from './detectCode'
export { looksLikeCode } from './looksLikeCode'
export { detectColor } from './detectColor'
export { detectEmail } from './detectEmail'
export { detectJson } from './detectJson'
export { detectShellCommand } from './detectShellCommand'
export { detectFilePath } from './detectFilePath'
export { detectPhoneNumber } from './detectPhoneNumber'
export { guessLanguage, type GuessedLanguage } from './language-guessers'
