export const PROMPTS_APP_CATEGORY_RAIL_STORAGE_KEY =
  'promptsApp.categoryRail.width'
export const PROMPTS_APP_CATEGORY_RAIL_MIN_WIDTH = 140
export const PROMPTS_APP_CATEGORY_RAIL_MAX_WIDTH = 380
export const PROMPTS_APP_CATEGORY_RAIL_DEFAULT_WIDTH = 200
