import type { ShortcutDef } from '@/frameworks/keyboard-shortcut/KeyboardShortcut.types'

export const DAILYPLAN_ACTIONS_SHORTCUTS: ShortcutDef[] = [
  {
    id: 'dailyplan.newTask',
    label: 'New Task',
    description: 'Open the new task dialog',
    scope: 'global',
    defaultKeys: 'N',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.newMeeting',
    label: 'New Meeting',
    description: 'Open the new meeting dialog',
    scope: 'global',
    defaultKeys: 'M',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.goToToday',
    label: 'Go to Today',
    description: 'Navigate to today\'s date',
    scope: 'global',
    defaultKeys: 'T',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.prevDay',
    label: 'Previous Day',
    description: 'Navigate to the previous day',
    scope: 'global',
    defaultKeys: 'Shift+ArrowLeft',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.nextDay',
    label: 'Next Day',
    description: 'Navigate to the next day',
    scope: 'global',
    defaultKeys: 'Shift+ArrowRight',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.viewDay',
    label: 'Day View',
    description: 'Switch to day view',
    scope: 'global',
    defaultKeys: 'Shift+1',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.viewWeek',
    label: 'Week View',
    description: 'Switch to week view',
    scope: 'global',
    defaultKeys: 'Shift+2',
    category: 'Daily Plan',
    allowInInput: false,
  },
  {
    id: 'dailyplan.viewMonth',
    label: 'Month View',
    description: 'Switch to month view',
    scope: 'global',
    defaultKeys: 'Shift+3',
    category: 'Daily Plan',
    allowInInput: false,
  },
]
