export const TOOL_LABELS: Record<string, string> = {
  list_directory: "List directory",
  read_file: "Read file",
  find_files: "Find files",
  grep_search: "Search text",
  get_disk_usage: "Disk usage",
  get_file_info: "File info",
  git_status: "Git status",
  git_log: "Git log",
  git_diff: "Git diff",
  git_show_commit: "Git show commit",
  git_branches: "Git branches",
  create_file: "Create file",
  create_folder: "Create folder",
  delete_item: "Delete item",
  rename_item: "Rename item",
  move_item: "Move item",
  copy_item: "Copy item",
  run_shell_command: "Run command",
} as const;
