export const dailyPlanSearchPanelStyles = {
  root: 'flex flex-col h-full',
  header: 'shrink-0 px-3 pt-3 pb-3',
  inputWrapper: 'flex items-center gap-1.5 bg-secondary/50 rounded-xl h-9 px-3 border border-transparent focus-within:border-input focus-within:ring-1 focus-within:ring-ring/20 transition-all duration-200',
  input: 'flex-1 min-w-0 bg-transparent text-[13px] text-foreground placeholder:text-muted-foreground/40 outline-none',
  clearButton: 'shrink-0 w-5 h-5 flex items-center justify-center rounded-md hover:bg-foreground/10 text-muted-foreground/40 hover:text-foreground/70 transition-colors cursor-pointer',
  statsRow: 'flex items-center justify-between px-3 py-1.5',
  statsText: 'text-[10px] font-medium text-muted-foreground/40 uppercase tracking-wider',
  resultsList: 'flex-1 overflow-y-auto',
  emptyState: 'flex flex-col items-center justify-center h-full text-muted-foreground/40 px-8 gap-2',
  emptyText: 'text-xs text-center',
  showMoreWrapper: 'px-3 py-3',
  showMoreButton: 'w-full h-8 flex items-center justify-center gap-2 rounded-lg text-xs font-medium text-muted-foreground hover:text-foreground bg-secondary/40 hover:bg-secondary/70 transition-colors cursor-pointer border border-border/30',
} as const

export const searchResultItemStyles = {
  base: 'w-full text-left px-3 py-2.5 transition-all duration-100 cursor-pointer hover:bg-secondary/40',
  titleRow: 'flex items-center gap-2',
  title: 'text-[13px] font-medium text-foreground truncate flex-1',
  badge: 'shrink-0 text-[9px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded-md',
  taskBadge: 'bg-blue-500/10 text-blue-400',
  meetingBadge: 'bg-purple-500/10 text-purple-400',
  metaRow: 'flex items-center gap-2 mt-1',
  date: 'text-[11px] text-muted-foreground/60',
  separator: 'text-[11px] text-muted-foreground/30',
  priority: 'text-[10px] font-medium uppercase tracking-wider',
  priorityLow: 'text-muted-foreground/40',
  priorityMedium: 'text-yellow-400/70',
  priorityHigh: 'text-orange-400/70',
  priorityUrgent: 'text-red-400/70',
  priorityCritical: 'text-red-400/70',
  status: 'text-[10px] text-muted-foreground/50',
  divider: 'mx-3 h-px bg-border/20',
} as const
