export const TERMINAL_LETTER_SPACING_MIN = -2
export const TERMINAL_LETTER_SPACING_MAX = 4
export const TERMINAL_LETTER_SPACING_DEFAULT = 0
export const TERMINAL_LETTER_SPACING_STEP = 0.1
export const TERMINAL_LETTER_SPACING_DECIMALS = 1
