import './bootstrap/registerAllEntityHandlers'

export type { EntityLinkHandler, EntityType, ParsedEntityHref } from './entity-links.types'
export { ENTITY_HREF_PREFIX, ENTITY_TOKEN_REGEX } from './entity-links.constants'
export { registerEntityLink } from './registry/registerEntityLink'
export { getEntityLink } from './registry/getEntityLink'
export { formatEntityToken } from './token/formatEntityToken'
export { parseEntityToken } from './token/parseEntityToken'
export { buildEntityHref } from './token/buildEntityHref'
export { parseEntityHref } from './token/parseEntityHref'
export { registerAllEntityHandlers } from './bootstrap/registerAllEntityHandlers'
export { ENTITY_TOKEN_PROMPT_RULE } from '@/prompts/entityTokenPromptRule'
